name: Literatural Fruit
favicon: null
layout_spectrum: 0.8087686167564243
typography_spectrum: 0.082843828946352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8271002620458603
  lightness: 0.40865530422888696
  saturation: 0.10825324687175453
  rhythmicContrast: 0.7851020474918187
purpose: []
